(()=>{'use strict';
const posts=APP_DATA, A=APP_ASSETS, M=MockupModel;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const paths={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',grid:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',reels:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="M3 9h18M7 3l4 6M15 3l4 6m-9 3 6 3-6 3Z"/>',carousel:'<rect x="7" y="3" width="14" height="14" rx="2" fill="currentColor" stroke-width="0"/><path d="M3 7v12a2 2 0 0 0 2 2h12"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',save:'<path d="M5 3h14v18l-7-5-7 5Z"/>',story:'<circle cx="12" cy="12" r="9" stroke-dasharray="12 3"/><path d="m10 8 6 4-6 4Z"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',left:'<path d="m15 5-7 7 7 7"/>',right:'<path d="m9 5 7 7-7 7"/>',up:'<path d="m5 15 7-7 7 7"/>',down:'<path d="m5 9 7 7 7-7"/>',link:'<path d="M10 13a5 5 0 0 0 7 .3l3-3a5 5 0 0 0-7-7l-2 2M14 11a5 5 0 0 0-7-.3l-3 3a5 5 0 0 0 7 7l2-2"/>',sliders:'<path d="M4 7h4m4 0h8M4 17h8m4 0h4"/><circle cx="10" cy="7" r="2"/><circle cx="14" cy="17" r="2"/>',file:'<path d="M14 3H5v18h14V8Zm0 0v5h5M8 12h8M8 16h6"/>',back:'<path d="m10 5-7 7 7 7M3 12h18"/>',book:'<path d="M3 4h6a4 4 0 0 1 3 2 4 4 0 0 1 3-2h6v16h-6a4 4 0 0 0-3 1 4 4 0 0 0-3-1H3ZM12 6v15"/>',quote:'<path d="M4 6h6v7H6v5H3v-7Zm11 0h6v7h-4v5h-3v-7Z"/>',arrow:'<path d="M5 19 19 5M5 5h14v14"/>'};
function icon(n,fill=false){return `<svg viewBox="0 0 24 24" fill="${fill?'currentColor':'none'}" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[n]||paths.grid}</svg>`;}
function btn(n,label,attrs='',klass=''){return `<button class="icon-button ${klass}" aria-label="${esc(label)}" title="${esc(label)}" ${attrs}>${icon(n)}</button>`;}
const dayMigration={"2": 1, "1": 2, "5": 3, "3": 4, "6": 5, "4": 6, "9": 8, "8": 9, "11": 10, "10": 11, "14": 12, "12": 13, "16": 14, "13": 15, "17": 16, "15": 17, "20": 18, "18": 19, "23": 20, "19": 22, "24": 23, "22": 24, "25": 25, "26": 26, "28": 27, "27": 28, "29": 29, "30": 30, "31": 31, "7": 7, "21": 21};try{if(!localStorage.getItem('lloyd-ig-alternating-v1')){for(const k of ['liked','saved']){const name='lloyd-ig-preview-'+k;const values=JSON.parse(localStorage.getItem(name)||'[]');localStorage.setItem(name,JSON.stringify(values.map(d=>dayMigration[d]||d)));}localStorage.setItem('lloyd-ig-alternating-v1','1');}}catch{}
function loadSet(k){try{return new Set(JSON.parse(localStorage.getItem('lloyd-ig-preview-'+k)||'[]').filter(n=>posts.some(p=>p.day===n)));}catch{return new Set();}}
const state={route:'profile',tab:'all',order:'latest',funnel:'all',labels:false,crop:'45',settings:false,liked:loadSet('liked'),saved:loadSet('saved'),slides:new Map(),post:null,reel:0,story:0,returnRoute:'profile'};
const stories=M.storyFrames(posts),reels=M.visible(posts,{kind:'Reel'});let toastTimer;let lastSwipe=0;
const profileAvatar=(cls='mini-avatar')=>`<img class="${cls}" src="${A.avatar}" alt="Lloyd Edge">`;
function notify(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2300);}
function navItems(){return [['feed','home','Home'],['reels/30','reels','Reels'],['stories','story','Stories'],['saved','save','Saved'],['profile','profile','Profile']].map(([r,i,t])=>`<button class="nav-item" data-nav="${r}">${i==='profile'?profileAvatar():icon(i)}<span>${t}</span></button>`).join('');}
$('#railNav').innerHTML=navItems();$('#mobileNav').innerHTML=navItems();$('#railLogo').src=A.logo;$('#mobileProfile').innerHTML=profileAvatar();
function navigate(r){location.hash='/'+r;}
function replaceRoute(r){history.replaceState(null,'','#/'+r);route();}
function markNav(r){document.querySelectorAll('.nav-item').forEach(b=>{const br=b.dataset.nav.split('/')[0];const active=br===r.split('/')[0]||(br==='profile'&&r.startsWith('collection'));b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');});}
function controls(){return `<div class="review-controls" id="reviewControls" ${state.settings?'':'hidden'}><label>Post order<select id="order"><option value="latest" ${state.order==='latest'?'selected':''}>Newest first</option><option value="earliest" ${state.order==='earliest'?'selected':''}>Day 01 first</option></select></label><label>Funnel<select id="funnel">${['all','TOF','MOF','BOF'].map(v=>`<option value="${v}" ${v===state.funnel?'selected':''}>${v==='all'?'All stages':v}</option>`).join('')}</select></label><label>Grid crop<select id="crop"><option value="45" ${state.crop==='45'?'selected':''}>4:5 artwork</option><option value="34" ${state.crop==='34'?'selected':''}>3:4 crop preview</option></select></label><label class="check"><input id="labels" type="checkbox" ${state.labels?'checked':''}>Show day + funnel</label></div>`;}
function visible(overrides={}){return M.visible(posts,{kind:state.tab,funnel:state.funnel,order:state.order,saved:[...state.saved],...overrides});}
function tile(p){return `<button class="tile" data-open="${p.day}" aria-label="Open Day ${p.day}: ${esc(p.topic)}"><img src="${p.thumbnail||p.images[0]}" alt="${esc(p.topic)}" loading="lazy" decoding="async">${p.kind==='Reel'||p.kind==='Carousel'?`<span class="type-icon">${icon(p.kind==='Reel'?'reels':'carousel')}</span>`:''}<span class="daylabel">Day ${String(p.day).padStart(2,'0')} · ${p.funnel}</span></button>`;}
function empty(saved=false){return `<div class="empty">${icon(saved?'save':'grid')}<h2>${saved?'Your saved posts':'No posts in this view'}</h2><p>${saved?'Tap the bookmark on a post to keep it here.':'Choose another funnel or post type.'}</p>${saved?'<p>Saved selections stay in this browser.</p>':''}</div>`;}
function grid(ps,saved=false){return `<div class="grid">${ps.length?ps.map(tile).join(''):empty(saved)}</div>`;}
function renderProfile(){const ps=visible();$('#main').innerHTML=`<div class="content"><section class="profile"><button class="avatar-button" data-story="7" aria-label="View Lloyd’s planned Stories">${profileAvatar('avatar')}</button><div><div class="profile-heading"><h1>lloydedge_buyersagent</h1><button class="button" data-nav="feed">View feed</button><button class="button secondary" data-nav="reels/30">Reels</button></div><div class="stats"><span><b>${M.visible(posts).length}</b> feed posts</span><span><b>14</b> Reel covers</span><span><b>2</b> Story days</span></div><div class="bio"><strong>Lloyd Edge</strong><p>🏆 REINSW Buyer’s Agent Of The Year 2024</p><p>📘 2 x Best-Selling Author</p><p>📞 1800 146 837</p><p>👇 Book A Complimentary Discovery Call</p><a href="https://linktr.ee/ausproppro" target="_blank" rel="noopener noreferrer">${icon('link')} linktr.ee/ausproppro</a></div></div></section><div class="highlights">${A.highlights.map(h=>{const content=`<span class="ring"><span><img src="${h.image}" alt=""></span></span>${esc(h.label)}`;return h.route?`<button class="highlight" data-nav="${esc(h.route)}" aria-label="Open ${esc(h.label)}">${content}</button>`:`<a class="highlight" href="${esc(h.url)}" target="_blank" rel="noopener noreferrer" aria-label="Open ${esc(h.label)}">${content}</a>`;}).join('')}</div><div class="resource-shortcuts"><button data-nav="collection/guide">${icon('file')} Free property checklist</button><button data-nav="collection/clients">${icon('quote')} Client testimonials</button></div><div class="grid-toolbar"><div class="tabs" role="tablist" aria-label="Profile content">${[['all','grid','POSTS'],['Reel','reels','REELS'],['saved','save','SAVED']].map(([k,i,l])=>`<button class="tab ${state.tab===k?'active':''}" role="tab" aria-selected="${state.tab===k}" data-tab="${k}">${icon(i)}${l}</button>`).join('')}</div>${btn('sliders','Review settings','data-settings','settings')}</div>${controls()}${grid(state.tab==='saved'?visible({kind:'all',collection:'saved'}):ps,state.tab==='saved')}<p class="page-note">30-day plan + bonus book post · Planned posts only. Bio matches the supplied Instagram screenshot. Highlights are proposed.<br>Static/carousel posts alternate with Reels. Stories sit outside the feed. Reel previews show thumbnails; filming scripts are included.</p></div>`;applyBody();}
function header(p,openButton=false){return `<div class="post-header">${profileAvatar()}<div class="byline"><strong>lloydedge_buyersagent</strong><small>Day ${String(p.day).padStart(2,'0')} · ${p.funnel} · ${p.kind==='Reel'?'Reel cover':p.contentKind==='testimonial'?'Client testimonial':p.kind}</small></div>${openButton?btn('arrow','Open post',`data-open="${p.day}"`):''}</div>`;}
function media(p,context='feed'){const n=state.slides.get(p.day)||0;return `<div class="media-stage" data-swipe="${p.day}" data-context="${context}"><img class="post-image" src="${p.images[n]}" alt="Day ${p.day}: ${esc(p.topic)}${p.images.length>1?`, slide ${n+1} of ${p.images.length}`:''}" ${context==='feed'?'loading="lazy"':''} draggable="false">${p.images.length>1?`<button class="slide-arrow prev" data-slide="${p.day}" data-delta="-1" aria-label="Previous slide" ${n===0?'hidden':''}>${icon('left')}</button><button class="slide-arrow next" data-slide="${p.day}" data-delta="1" aria-label="Next slide" ${n===p.images.length-1?'hidden':''}>${icon('right')}</button><span class="slide-counter">${n+1} / ${p.images.length}</span>`:''}</div>`;}
function actions(p){return `<div class="action-row"><button class="icon-button like-action ${state.liked.has(p.day)?'is-active':''}" data-like="${p.day}" aria-label="${state.liked.has(p.day)?'Unlike':'Like'} in this preview" aria-pressed="${state.liked.has(p.day)}">${icon('heart',state.liked.has(p.day))}</button>${p.kind==='Reel'?btn('file','Read filming script',`data-script="${p.day}"`):''}<button class="icon-button save-action" data-save="${p.day}" aria-label="${state.saved.has(p.day)?'Unsave':'Save'} post" aria-pressed="${state.saved.has(p.day)}">${icon('save',state.saved.has(p.day))}</button></div>`;}
function dots(p){return p.images.length<2?'':`<div class="dots" data-dots="${p.day}">${p.images.map((_,i)=>`<button class="dot-btn ${i===(state.slides.get(p.day)||0)?'active':''}" aria-label="Go to slide ${i+1}" data-slide-to="${p.day}" data-index="${i}"></button>`).join('')}</div>`;}
function captionHTML(text){return esc(text).replace(/https:\/\/[^\s<]+/g,u=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${u}</a>`);}
function caption(p,full=false){const text=p.caption;return `<div class="caption"><strong>lloydedge_buyersagent</strong> ${captionHTML(full||text.length<210?text:text.slice(0,185).trim()+'…')}${!full&&text.length>=210?` <button class="more" data-expand="${p.day}">more</button>`:''}</div>`;}
function renderFeed(){state.tab='all';const ps=visible();$('#main').innerHTML=`<div class="feed"><div class="collection-head"><h1>Home</h1>${btn('sliders','Review settings','data-settings')}</div>${controls()}${ps.map(p=>`<article class="feed-card" data-feed-day="${p.day}">${header(p,true)}${media(p)}${dots(p)}${actions(p)}${caption(p)}<div class="post-meta">${p.kind==='Reel'?`<button class="button secondary" data-reel="${p.day}">Open Reel cover</button>`:'Planned post · September content preview'}</div></article>`).join('')||empty()}</div>`;applyBody();}
const collections={guide:{title:'Free property checklist',desc:'Before You Offer · Four-page fillable PDF · MOF',days:[14]},success:{title:'Success stories',desc:'Three investment cases · BOF',days:[3,18,20]},clients:{title:'Client voices',desc:'Attributed client testimonials · BOF',days:[12,25]},books:{title:'Books',desc:'Reading prompts and Set for Life',days:[27,31]}};
function renderCollection(key){const c=collections[key]||collections.success;$('#main').innerHTML=`<div class="content"><div class="collection-head">${btn('back','Back to profile','data-nav="profile"')}<div><h1>${c.title}</h1><p>${c.desc}</p></div></div>${grid(M.visible(posts,{collection:c.days,order:state.order}))}</div>`;applyBody();}
function renderSaved(){const ps=M.visible(posts,{collection:'saved',saved:[...state.saved],order:state.order});$('#main').innerHTML=`<div class="content"><div class="collection-head"><div><h1>Saved</h1><p>Your selections in this browser</p></div></div>${grid(ps,true)}</div>`;applyBody();}
function renderStories(){const ps=posts.filter(p=>p.kind==='Story');$('#main').innerHTML=`<div class="content"><div class="collection-head"><div><h1>Stories</h1><p>Two planned sequences · Three frames each</p></div></div><div class="stories-menu">${ps.map(p=>`<button class="story-card" data-story="${p.day}"><img src="${p.images[0]}" alt="Day ${p.day} Story cover"><span class="story-card-label"><strong>Day ${p.day} · Ask Lloyd</strong>${esc(p.topic)}</span></button>`).join('')}</div><p class="page-note">Poll choices are artwork previews. Native Instagram stickers are added when posting.</p></div>`;}
function applyBody(){document.body.classList.toggle('showlabels',state.labels);document.body.classList.toggle('crop34',state.crop==='34');}
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.body.style.overflow='';}
function showDialog(id){const d=$(id);if(!d.open)d.showModal();document.body.style.overflow='hidden';}
function dismiss(){closeDialogs();state.post=null;history.replaceState(null,'','#/'+state.returnRoute);route(false);}
function postSequence(){const c=state.returnRoute.startsWith('collection/')?collections[state.returnRoute.split('/')[1]]:null;return c?M.visible(posts,{collection:c.days,order:state.order}):visible({kind:state.tab==='Reel'?'Reel':'all',collection:state.returnRoute==='saved'||state.tab==='saved'?'saved':null});}
function openPost(day){const p=posts.find(p=>p.day===day&&p.kind!=='Story');if(!p)return;state.post=p;const seq=postSequence(),i=seq.findIndex(x=>x.day===day);$('#postDialog').innerHTML=`${btn('close','Close post','data-dismiss','dialog-close')}${btn('left','Previous post','data-post-step="-1" '+(i<=0?'disabled':''),'outside-prev')}${btn('right','Next post','data-post-step="1" '+(i<0||i>=seq.length-1?'disabled':''),'outside-next')}<div class="post-dialog-layout">${media(p,'dialog')}<div class="post-panel">${header(p)}${caption(p,true)}${dots(p)}${actions(p)}<div class="post-meta">${p.kind==='Reel'?`<button class="button secondary" data-reel="${day}">Open vertical Reel cover</button>`:'Planned post · September content preview'}</div>${p.contentKind==='leadMagnet'&&A.leadMagnet?`<a class="post-link" href="${A.leadMagnet}" download="${esc(A.leadMagnetName)}">${icon('file')} Download the free checklist (PDF)</a>`:''}${p.purchaseUrl?`<a class="post-link" href="${esc(p.purchaseUrl)}" target="_blank" rel="noopener noreferrer">${icon('book')} Buy on Amazon Australia</a>`:''}${p.source?`<a class="post-link" href="${esc(p.source)}" target="_blank" rel="noopener noreferrer">${icon('link')} Read the original source</a>`:''}</div></div>`;showDialog('#postDialog');}
function moveSlide(day,delta,absolute){const p=posts.find(p=>p.day===day);const n=absolute===undefined?M.step(state.slides.get(day)||0,delta,p.images.length):M.step(absolute,0,p.images.length);state.slides.set(day,n);document.querySelectorAll(`[data-swipe="${day}"]`).forEach(stage=>{stage.querySelector('.post-image').src=p.images[n];stage.querySelector('.post-image').alt=`Day ${day}: ${p.topic}, slide ${n+1} of ${p.images.length}`;if(p.images.length>1){stage.querySelector('.prev').hidden=n===0;stage.querySelector('.next').hidden=n===p.images.length-1;stage.querySelector('.slide-counter').textContent=`${n+1} / ${p.images.length}`;}});document.querySelectorAll(`[data-dots="${day}"] .dot-btn`).forEach(b=>b.classList.toggle('active',Number(b.dataset.index)===n));}
function movePost(delta){const seq=postSequence(),i=seq.findIndex(p=>p.day===state.post?.day),p=seq[M.step(i,delta,seq.length)];if(p){history.replaceState(null,'','#/post/'+p.day);openPost(p.day);}}
function openReel(day){state.reel=Math.max(0,reels.findIndex(p=>p.day===day));const p=reels[state.reel];$('#reelDialog').innerHTML=`${btn('close','Close Reel preview','data-dismiss','dialog-close')}<div class="immersive"><div class="reel-phone" data-reel-swipe><img src="${p.verticalCover||p.images[0]}" alt="Day ${p.day}: ${esc(p.topic)} — Reel thumbnail"><div class="viewer-top">${profileAvatar()}<strong>lloydedge_buyersagent</strong><span class="viewer-tag">Day ${p.day} · ${p.funnel}</span></div><div class="reel-overlay"><strong>${esc(p.topic)}</strong><p>Thumbnail preview · ${state.reel+1} of ${reels.length} Reels</p><button class="button" data-script="${p.day}">${icon('file')}Read filming script</button><button class="button secondary" data-open="${p.day}">Caption</button></div></div><div class="reel-actions">${actions(p)}</div><div class="viewer-navigation">${btn('up','Previous Reel','data-reel-step="-1" '+(state.reel===0?'disabled':''))}${btn('down','Next Reel','data-reel-step="1" '+(state.reel===reels.length-1?'disabled':''))}</div></div>`;$('#reelDialog .reel-actions .action-row').style.cssText='display:grid;padding:0;gap:14px;border:0';showDialog('#reelDialog');}
function moveReel(delta){const n=M.step(state.reel,delta,reels.length);history.replaceState(null,'','#/reels/'+reels[n].day);openReel(reels[n].day);}
function openStory(day,index=0){const n=stories.findIndex(s=>s.day===day&&s.index===index);state.story=Math.max(0,n);const f=stories[state.story];$('#storyDialog').innerHTML=`${btn('close','Close Story','data-dismiss','dialog-close')}<div class="immersive"><div class="story-phone" data-story-swipe><img src="${f.src}" alt="Day ${f.day}, Story frame ${f.index+1} of ${f.total}"><div class="story-progress">${Array.from({length:f.total},(_,i)=>`<button class="${i<=f.index?'passed':''}" data-story-frame="${i}" aria-label="Story frame ${i+1}"></button>`).join('')}</div><div class="viewer-top">${profileAvatar()}<strong>lloydedge_buyersagent</strong><span class="viewer-tag">Day ${f.day} · ${f.index+1}/${f.total}</span></div><button class="story-tap left" aria-label="Previous Story frame" data-story-step="-1" ${state.story===0?'disabled':''}></button><button class="story-tap right" aria-label="Next Story frame" data-story-step="1"></button><div class="story-bottom">Story artwork preview · Tap the sides to navigate</div></div><div class="story-navigation">${btn('left','Previous Story','data-story-step="-1" '+(state.story===0?'disabled':''))}${btn('right',state.story===stories.length-1?'Finish Stories':'Next Story','data-story-step="1"')}</div></div>`;showDialog('#storyDialog');}
function moveStory(delta){if(state.story+delta>=stories.length){dismiss();return;}const f=stories[M.step(state.story,delta,stories.length)];history.replaceState(null,'','#/story/'+f.day+'/'+f.index);openStory(f.day,f.index);}
function script(day){const p=posts.find(p=>p.day===day);if(!p?.script)return;$('#scriptDialog').innerHTML=`${btn('close','Close script','data-close-script')}<h2>Day ${day} · Filming script</h2><div class="script-copy">${esc(p.script)}</div><a class="button" download="Day_${String(day).padStart(2,'0')}_${p.funnel}_Reel_Script.txt" href="data:text/plain;charset=utf-8,${encodeURIComponent(p.script)}">Download script</a>`;showDialog('#scriptDialog');}
function toggle(kind,day){const set=state[kind];set.has(day)?set.delete(day):set.add(day);try{localStorage.setItem('lloyd-ig-preview-'+kind,JSON.stringify([...set]));}catch{}const active=set.has(day),attr=kind==='liked'?'like':'save';document.querySelectorAll(`[data-${attr}="${day}"]`).forEach(b=>{b.innerHTML=icon(kind==='liked'?'heart':'save',active);b.setAttribute('aria-pressed',String(active));b.setAttribute('aria-label',kind==='liked'?(active?'Unlike':'Like')+' in this preview':(active?'Unsave':'Save')+' post');if(kind==='liked')b.classList.toggle('is-active',active);});notify(kind==='saved'?(active?'Saved in this preview':'Removed from saved posts'):(active?'Liked in this preview':'Like removed'));if(kind==='saved'&&!$('#postDialog').open&&(state.route==='saved'||state.tab==='saved'))renderMain();}
function renderMain(){if(state.route==='feed')renderFeed();else if(state.route==='saved')renderSaved();else if(state.route==='stories')renderStories();else if(state.route.startsWith('collection/'))renderCollection(state.route.split('/')[1]);else renderProfile();}
function route(scroll=true){const r=decodeURIComponent(location.hash.replace(/^#\/?/,'')||'profile'),parts=r.split('/');if(['post','reels','story'].includes(parts[0])){if(!$('#main').innerHTML)renderProfile();$('#scriptDialog').close();if(parts[0]==='post'){$('#reelDialog').close();$('#storyDialog').close();openPost(Number(parts[1]));}else if(parts[0]==='reels'){$('#postDialog').close();$('#storyDialog').close();openReel(Number(parts[1]||30));markNav('reels');}else{$('#postDialog').close();$('#reelDialog').close();openStory(Number(parts[1]||7),Number(parts[2]||0));}return;}closeDialogs();state.route=r;state.returnRoute=r;if(r==='profile/reels')state.tab='Reel';else if(r==='profile/saved')state.tab='saved';else if(r==='profile')state.tab='all';renderMain();markNav(r);if(scroll)window.scrollTo(0,0);}
document.addEventListener('click',e=>{if(Date.now()-lastSwipe<300){e.preventDefault();return;}const b=e.target.closest('button,[data-nav]');if(!b)return;const d=b.dataset;if(d.nav){navigate(d.nav);return;}if(d.tab){navigate(d.tab==='Reel'?'profile/reels':d.tab==='saved'?'profile/saved':'profile');return;}if('settings'in d){state.settings=!state.settings;const c=$('#reviewControls');if(c)c.hidden=!state.settings;return;}if(d.open){const p=posts.find(x=>x.day===Number(d.open));if(p?.kind==='Reel'&&state.tab==='Reel'&&!$('#reelDialog').open)navigate('reels/'+p.day);else navigate('post/'+d.open);return;}if(d.reel){navigate('reels/'+d.reel);return;}if(d.story){navigate('story/'+d.story+'/0');return;}if('dismiss'in d){dismiss();return;}if(d.slide){moveSlide(Number(d.slide),Number(d.delta));return;}if(d.slideTo){moveSlide(Number(d.slideTo),0,Number(d.index));return;}if(d.postStep){movePost(Number(d.postStep));return;}if(d.reelStep){moveReel(Number(d.reelStep));return;}if(d.storyStep){moveStory(Number(d.storyStep));return;}if('storyFrame'in d){openStory(stories[state.story].day,Number(d.storyFrame));return;}if(d.like){toggle('liked',Number(d.like));return;}if(d.save){toggle('saved',Number(d.save));return;}if(d.script){script(Number(d.script));return;}if('closeScript'in d){$('#scriptDialog').close();if(!document.querySelector('dialog[open]'))document.body.style.overflow='';return;}if(d.expand){b.closest('.caption').outerHTML=caption(posts.find(p=>p.day===Number(d.expand)),true);}});
document.addEventListener('change',e=>{if(e.target.id==='order')state.order=e.target.value;else if(e.target.id==='funnel')state.funnel=e.target.value;else if(e.target.id==='crop')state.crop=e.target.value;else if(e.target.id==='labels')state.labels=e.target.checked;else return;renderMain();});
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('cancel',e=>{e.preventDefault();if(d.id==='scriptDialog'){d.close();if(!document.querySelector('dialog[open]'))document.body.style.overflow='';}else dismiss();});d.addEventListener('click',e=>{if(e.target===d&&d.id==='postDialog')dismiss();});});
document.addEventListener('keydown',e=>{if($('#scriptDialog').open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if($('#storyDialog').open&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();moveStory(e.key==='ArrowLeft'?-1:1);}else if($('#reelDialog').open&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();moveReel(e.key==='ArrowUp'?-1:1);}else if($('#postDialog').open){if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();if(state.post.images.length>1)moveSlide(state.post.day,e.key==='ArrowLeft'?-1:1);else movePost(e.key==='ArrowLeft'?-1:1);}else if(['PageUp','PageDown'].includes(e.key)){e.preventDefault();movePost(e.key==='PageUp'?-1:1);}}});
let pointer=null;document.addEventListener('pointerdown',e=>{const stage=e.target.closest('[data-swipe],[data-reel-swipe],[data-story-swipe]');if(stage)pointer={x:e.clientX,y:e.clientY,stage};});document.addEventListener('pointerup',e=>{if(!pointer)return;const {x,y,stage}=pointer;pointer=null;const dx=e.clientX-x,dy=e.clientY-y;if(stage.hasAttribute('data-reel-swipe')&&Math.abs(dy)>65&&Math.abs(dy)>Math.abs(dx)){lastSwipe=Date.now();moveReel(dy>0?-1:1);}else if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)){lastSwipe=Date.now();if(stage.hasAttribute('data-story-swipe'))moveStory(dx>0?-1:1);else if(stage.dataset.swipe)moveSlide(Number(stage.dataset.swipe),dx>0?-1:1);}});document.addEventListener('pointercancel',()=>pointer=null);
window.addEventListener('hashchange',()=>route());route();
})();
